# Generated by Django 5.0.1 on 2024-02-01 09:37

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Regel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("aangemaakt_op", models.DateTimeField(auto_now_add=True)),
                ("aangepast_op", models.DateTimeField(auto_now=True)),
                ("onderwerp_url", models.URLField(unique=True)),
                (
                    "afstand",
                    models.PositiveIntegerField(
                        help_text="De straal om de binnenkomende gps coordinaten in meters"
                    ),
                ),
                (
                    "tijd",
                    models.PositiveIntegerField(
                        help_text="Tijd in seconden na de het begin van de melding"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
