# Generated by Django 5.0.1 on 2024-02-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="regel",
            name="afstand",
        ),
        migrations.RemoveField(
            model_name="regel",
            name="tijd",
        ),
        migrations.AddField(
            model_name="regel",
            name="deduplicate",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="regel",
            name="distance",
            field=models.PositiveIntegerField(
                default=30,
                help_text="De straal om de binnenkomende gps coordinaten in meters",
            ),
        ),
        migrations.AddField(
            model_name="regel",
            name="max_age",
            field=models.PositiveIntegerField(
                default=864000,
                help_text="Tijd in seconden na de het begin van de melding",
            ),
        ),
    ]
