# Generated by Django 5.2.8 on 2025-11-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_remove_regel_afstand_remove_regel_tijd_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="regel",
            name="max_age",
            field=models.PositiveIntegerField(
                default=864000, help_text="Tijd in seconden na het begin van de melding"
            ),
        ),
    ]
