# Generated by Django 5.0.1 on 2024-02-08 13:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authorisatie", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="permissie",
            options={
                "default_permissions": (),
                "managed": False,
                "permissions": [
                    ("gebruiker_lijst_bekijken", "Gebruiker lijst bekijken"),
                    ("gebruiker_aanmaken", "Gebruiker aanmaken"),
                    ("gebruiker_aanpassen", "Gebruiker aanpassen"),
                    ("gebruiker_bekijken", "Gebruiker bekijken"),
                    ("gebruiker_verwijderen", "Gebruiker verwijderen"),
                    ("beheer_bekijken", "Beheer bekijken"),
                    ("rechtengroep_lijst_bekijken", "Rechtengroep lijst bekijken"),
                    ("rechtengroep_aanmaken", "Rechtengroep aanmaken"),
                    ("rechtengroep_bekijken", "Rechtengroep bekijken"),
                    ("rechtengroep_aanpassen", "Rechtengroep aanpassen"),
                    ("rechtengroep_verwijderen", "Rechtengroep verwijderen"),
                    ("regel_lijst_bekijken", "Regel lijst bekijken"),
                    ("regel_aanmaken", "Regel aanmaken"),
                    ("regel_aanpassen", "Regel aanpassen"),
                    ("regel_verwijderen", "Regel verwijderen"),
                ],
            },
        ),
    ]
